config/routes.rb
Rails.application.routes.draw do
  root 'contacts#new'
  resource :contact, only: [:create, :new, :show]
  get 'policies/show', as: :policies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
require 'mail'

class Contact < ApplicationRecord
  EMAIL_LENGTH = {
    maximum: 254, # RFCs
    minimum: 3 # a@a
  }.freeze

  RESERVED_EMAIL = [
    'abuse', 'account', 'accounts', 'admin', 'administrator', 'contact',
    'contact-us', 'contactus', 'copyright', 'enquiry', 'faq', 'ftp', 'help',
    'hostmaster', 'imap', 'info', 'localdomain', 'localhost', 'login',
    'logout', 'mail', 'mailer-daemon', 'marketing', 'myaccount', 'news',
    'no-reply', 'nobody', 'noreply', 'payments', 'pop', 'pop3', 'postmaster',
    'preferences', 'pricing', 'privacy', 'profile', 'register', 'root',
    'sales', 'secure', 'security', 'settings', 'signin', 'signup', 'smtp',
    'ssl', 'ssladmin', 'ssladministrator', 'sslwebmaster', 'status',
    'subscribe', 'support', 'sysadmin', 'terms', 'tos', 'user', 'users',
    'webmail', 'webmaster', 'www'
  ].freeze

  validates :email, format: { with: /\A\S+@\S+\z/ }
  validates :email, length: EMAIL_LENGTH
  validate :normalized_email_uniqueness

  # The before_validation callback seems to work better than others for this.
  before_validation :set_normalized_email

  def normalized_email_uniqueness
    return unless self.class.where(normalized_email: normalized_email).exists?
    errors.add(:normalized_email, 'has already been taken')
    errors.add(:email, 'has already been taken')
  end

  def set_normalized_email
    self.normalized_email = email
      .yield_self { |e| normalize_unicode(e) }
      .downcase
      .yield_self { |e| remove_ignored_email_characters(e) }
      .tap { |e| check_reserved_email_addresses(e) }
  end

  private

  def normalize_unicode(email)
    email.unicode_normalize(:nfkc)
  rescue StandardError
    errors.add(:email, 'contains abnormal characters')
    throw :abort
  end

  def remove_ignored_email_characters(email)
    address = parse_email(email)
    # If address is invalid, let validators handle it.
    return unless address.local && address.domain
    [
      address.local.delete('.').sub(/\+.*/, ''),
      address.domain
    ].compact.join('@')
  end

  def check_reserved_email_addresses(email)
    return unless RESERVED_EMAIL.include?(parse_email(email).local)
    errors.add(:email, 'contains a prohibited username')
    throw :abort
  end

  def parse_email(email)
    Mail::Address.new(email)
  rescue StandardError
    errors.add(:email, 'has an abnormal format')
    throw :abort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    Subscriptions.new.subscribe(create_params)
    redirect_to(
      contact_path,
      flash: { contacts_create_success: true },
      status: :see_other
    )
  rescue Subscriptions::Error => exception
    flash.now.alert = exception.message
    @contact = build_contact(exception)
    render :new
  end

  def new
    @contact = Contact.new
  end

  def show
    redirect_to new_contact_path unless flash[:contacts_create_success]
  end

  private

  def create_params
    params.require(:contact).permit(:email)
  end

  def build_contact(exception)
    record_is_contact = defined?(exception.original_exception.record) &&
                        exception.original_exception.record.is_a?(Contact)
    record_is_contact ? exception.original_exception.record : Contact.new
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_title(string = nil)
    [string, 'Take Control of Your Career'].compact.join(' - ')
  end

  def field_error(model, attribute, options = {})
    return unless model.errors.include?(attribute)
    error = model.errors[attribute].first
    options[:prefix] ||= 'Field'
    tag.div(
      "#{options[:prefix]} #{error}.",
      class: ['field-error', options[:class]].compact.join(' ')
    )
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/contacts/new.html.erb
<div class="contacts-new">

  <div class="hero-wrapper">
    <div class="viewport-wrapper">
      <div class="content-wrapper">

        <div class="hero">

          <div class="hero-text-wrapper">

            <h1 class="hero-heading">Take Control of Your Career</h1>

            <div class="hero-statement-wrapper">
              <div class="hero-statement">
                Use our career management tools to find your ideal job, and then excel at it.
              </div>
            </div>

          </div>

          <div class="hero-image-wrapper">

            <picture>
              <source media="(max-width: 386px)" srcset="<%= image_path 'hero_301px.png' %>" />
              <source media="(min-width: 387px) and (max-width: 774px)" srcset="<%= image_path 'hero_900px.png' %>" />
              <source media="(min-width: 775px)" srcset="<%= image_path 'hero_600px.png' %>" />
              <%= image_tag 'hero_600px.png', alt: 'Job Seeker', class: 'hero-image' %>
            </picture>

          </div>

        </div>
      </div>

    </div>
  </div>

  <div class="viewport-wrapper">
    <div class="content-wrapper">
      <div class="benefits-wrapper">
        <div class="benefits">

          <div>

            <h2 class="benefit-heading">
              <%= icon('fas', 'smile', class: 'benefit-icon-smile') %>
              Reduce Fear
            </h2>

            <p class="benefit-statement">
              Eliminate your concerns about falling behind, or not being able to
              grab new opportunities. We'll help you <strong>discover and learn
              skills</strong> which are valuable to employers, so you can get the
              jobs and promotions you want.
            </p>

          </div>

          <div>

            <h2 class="benefit-heading">
              <%= icon('fas', 'file-medical-alt', class: 'benefit-icon-file-medical-alt') %>
              Reduce Stress
            </h2>

            <p class="benefit-statement">
              Get rid of the anxiety created when you try to <strong>manage the
              events and relationships in your professional life</strong>.
              We'll help you track things like the phases of a job application,
              meetups you want to attend, new people you want to stay in touch
              with, educational opportunities, and a lot more.
            </p>

          </div>

          <div>

            <h2 class="benefit-heading">
              <%= icon('fas', 'list-ol', class: 'benefit-icon-list-ol') %>
              Reduce Boredom
            </h2>

            <p class="benefit-statement">
              Limit the tedious work required to <strong>record, organize, and
              present your accomplishments</strong>. Whether it's filling out
              performance reviews, creating content for a good resume, or
              convincing your boss you deserve a raise, we've can help.
            </p>

          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="viewport-wrapper">
    <div class="content-wrapper">

      <div class="form-wrapper">
        <div class="form-inner-wrapper">

          <p class="form-statement">
            We're building a new web site named "Careerativity" that will
            provide these benefits and more. Subscribe to get news about our
            launch, and we'll give you a <strong><em>discount</em></strong>
            when you sign up!
          </p>

          <%= form_with(class: (!@contact.errors.empty? ? 'form form-with-errors' : 'form'), local: true, model: @contact, url: contact_path) do |f| %>

            <div>
              <%= f.label(:email, class: 'form-label') %>
              <br />
              <%= f.email_field(:email, class: 'form-field', placeholder: 'jsmith@example.com') %>
              <br />
              <%= field_error(@contact, :email, class: 'form-field-error', prefix: 'Email') %>
            </div>

            <div>
              <%= f.submit('Subscribe now!', class: 'form-button', data: { 'disable-with': 'Subscribing now ...' }) %>
            </div>


          <% end %>

          <div class="form-privacy">
            By subcribing, you agree to the
            <%= link_to 'Terms of Service and Privacy Policy', policies_path %>.
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<% content_for :title, build_title('Confirmation') %>

<div class="contacts-show">
  <div class="confirmation-content-wrapper">
    <div class="confirmation-wrapper">
      <div class="confirmation-content" data-t-notice-success>
        <p>
          You were successfully sign up! We're excited to show you the finished
          web site. We'll send you an email when it's ready.
        </p>

        <%= link_to new_contact_path do %>
          <%= icon('fas', 'redo-alt') %> Subscribe another email address
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">

    <% if Rails.env.production? %>

      <%= javascript_include_tag 'https://www.googletagmanager.com/gtag/js?id=UA-120838736-1', async: true %>

      <%= javascript_tag(nonce: true) do %>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-120838736-1');
      <% end %>

    <% end %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Careerativity helps you find the ideal job, and then excel at it.">

    <title><%= content_for(:title) || build_title %></title>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=v2">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=v2">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=v2">
    <link rel="manifest" href="/site.webmanifest?v=v2">
    <link rel="mask-icon" href="/safari-pinned-tab.svg?v=v2" color="#045fd6">
    <link rel="shortcut icon" href="/favicon.ico?v=v2">
    <meta name="msapplication-TileColor" content="#045fd6">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png?v=v2">
    <meta name="theme-color" content="#045fd6">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Raleway:400,700" rel="stylesheet" />

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', defer: true %>
  </head>

  <body>

    <noscript>
      <div style="background-color: rgba(189, 0, 20, 0.16); color: #bd0014; margin-bottom: 4rem; padding: 1rem; text-align: center; vertical-align: middle; width: 100vw">
        Please enable JavaScript to use this web site.
      </div>
    </noscript>

    <%= yield %>

  </body>

</html>

app/views/policies/show.html.erb
<div class="viewport-wrapper">
  <div class="content-wrapper">
    <div class="policies-show">
      <%= link_to root_path do %>
        <%= icon('fas', 'redo-alt') %> Back
      <% end %>

      <h1>Terms of Service and Privacy Policy</h1>

      <h2>Terms of Service</h2>

      <h3>1. Terms</h3>

      <p>
        By accessing the website at
        <a href="https://careerativity.com">https://careerativity.com</a>, you
        are agreeing to be bound by these terms of service, all applicable laws
        and regulations, and agree that you are responsible for compliance with
        any applicable local laws. If you do not agree with any of these terms,
        you are prohibited from using or accessing this site. The materials
        contained in this website are protected by applicable copyright and
        trademark law.
      </p>

      <h3>2. Use License</h3>

      <ol type="a">
        <li>
          Permission is granted to temporarily download one copy of the materials
          (information or software) on Careerativity's website for personal,
          non-commercial transitory viewing only. This is the grant of a license,
          not a transfer of title, and under this license you may not:

          <ol type="i">
              <li>modify or copy the materials;</li>
              <li>
                use the materials for any commercial purpose, or for any public
                display (commercial or non-commercial);
              </li>
              <li>
                attempt to decompile or reverse engineer any software contained
                on Careerativity's website;
              </li>
              <li>
                remove any copyright or other proprietary notations from the
                materials; or
              </li>
              <li>
                transfer the materials to another person or "mirror" the
                materials on any other server.
              </li>
          </ol>
        </li>

        <li>
          This license shall automatically terminate if you violate any of
          these restrictions and may be terminated by Skytop Software or
          Careerativity at any time. Upon terminating your viewing of these
          materials or upon the termination of this license, you must destroy
          any downloaded materials in your possession whether in electronic or
          printed format.
        </li>
      </ol>

      <h3>3. Disclaimer</h3>

      <ol type="a">
        <li>
          The materials on Careerativity's website are provided on an 'as is'
          basis. Skytop Software and Careerativity make no warranties,
          expressed or implied, and hereby disclaim and negate all other
          warranties including, without limitation, implied warranties or
          conditions of merchantability, fitness for a particular purpose, or
          non-infringement of intellectual property or other violation of
          rights.
        </li>

        <li>
          Further, Skytop Software and Careerativity do not warrant or make any
          representations concerning the accuracy, likely results, or
          reliability of the use of the materials on its website or otherwise
          relating to such materials or on any sites linked to this site.
        </li>
      </ol>

      <h3>4. Limitations</h3>

      <p>
        In no event shall Skytop Software or Careerativity or its suppliers be
        liable for any damages (including, without limitation, damages for loss
        of data or profit, or due to business interruption) arising out of the
        use or inability to use the materials on Careerativity's website, even
        if Skytop Software or Careerativity, or a Skytop Software or
        Careerativity authorized representative has been notified orally or in
        writing of the possibility of such damage. Because some jurisdictions
        do not allow limitations on implied warranties, or limitations of
        liability for consequential or incidental damages, these limitations
        may not apply to you.
      </p>

      <h3>5. Accuracy of materials</h3>

      <p>
        The materials appearing on Careerativity's website could include
        technical, typographical, or photographic errors. Skytop Software and
        Careerativity do not warrant that any of the materials on its website
        are accurate, complete or current. Skytop Software and Careerativity
        may make changes to the materials contained on its website at any time
        without notice. However, Skytop Software and Careerativity do not make
        any commitment to update the materials.
      </p>

      <h3>6. Links</h3>

      <p>
        Neither Skytop Software nor Careerativity have not reviewed all of the
        sites linked to its website and are not responsible for the contents of
        any such linked site. The inclusion of any link does not imply
        endorsement by Skytop Software or Careerativity of the site. Use of any
        such linked website is at the user's own risk.
      </p>

      <h3>7. Modifications</h3>

      <p>
        Skytop Software or Careerativity may revise these terms of service for
        its website at any time without notice. By using this website you are
        agreeing to be bound by the then current version of these terms of
        service.
      </p>

      <h3>8. Governing Law</h3>

      <p>
        These terms and conditions are governed by and construed in accordance
        with the laws of CO and you irrevocably submit to the exclusive
        jurisdiction of the courts in that State or location.
      </p>

      <h2>Privacy Policy</h2>

      <p>
        Your privacy is important to us. It is Skytop Software's and
        Careerativity's policy to respect your privacy regarding any
        information we may collect from you across our website,
        <a href="https://careerativity.com">https://careerativity.com</a>, and
        other sites we own and operate.
      </p>

      <p>
        We only ask for personal information when we truly need it to provide a
        service to you. We collect it by fair and lawful means, with your
        knowledge and consent. We also let you know why we’re collecting it and
        how it will be used.
      </p>

      <p>
        We only retain collected information for as long as necessary to provide
        you with your requested service. What data we store, we’ll protect within
        commercially acceptable means to prevent loss and theft, as well as
        unauthorised access, disclosure, copying, use or modification.
      </p>

      <p>
        We don’t share any personally identifying information publicly or with
        third-parties, except when required to by law.
      </p>

      <p>
        Our website may link to external sites that are not operated by us.
        Please be aware that we have no control over the content and practices of
        these sites, and cannot accept responsibility or liability for their
        respective privacy policies.
      </p>

      <p>
        You are free to refuse our request for your personal information, with
        the understanding that we may be unable to provide you with some of your
        desired services.
      </p>

      <p>
        Your continued use of our website will be regarded as acceptance of our
        practices around privacy and personal information. If you have any
        questions about how we handle user data and personal information, feel
        free to contact us at <%= mail_to 'careerativitybiz@gmail.com' %>.
      </p>

      <p>
        This policy is effective as of 4 June 2018.
      </p>
    </div>
  </div>
</div>